version: "3.8"

services:
  generador-imagen:
    build: .
    container_name: generador-imagen
    restart: always
    ports:
      - "3001:3000" # Usando el puerto 3001 en el host
    volumes:
      - ./public/images:/app/public/images
    environment:
      - NODE_ENV=production
      - PORT=3000
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
