version: "3.8"

services:
  generador-imagen:
    build: .
    container_name: generador-imagen
    restart: always
    ports:
      - "3001:3000" # Cambia 3000 por 3001 (o cualquier otro puerto libre)
    volumes:
      - ./public/images:/app/public/images
      - ./.env:/app/.env:ro
    environment:
      - NODE_ENV=production
      - PORT=3000
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
